const data ={
    products:[
        {
            _id:'1',
            name:'headphone',
            category:'shirts',
            image:'/images/p-1.jpeg',
            price:120,
            brand:'samsung',
            rating:4.5,
            numReviews:10,
            description:'highr quality product',
        },
        {
            _id:'2',
            name:'headphone-nokia',
            category:'shirts',
            image:'/images/p-1.jpeg',
            price:130,
            brand:'nokia',
            rating:4.5,
            numReviews:10,
            description:'highr quality product',
        },
        {
            _id:'3',
            name:'headphone',
            category:'shirts',
            image:'/images/p-1.jpeg',
            price:140,
            brand:'apple',
            rating:4.5,
            numReviews:10,
            description:'highr quality product',
        },
        {
            _id:'4',
            name:'headphone',
            category:'shirts',
            image:'/images/p-1.jpeg',
            price:150,
            brand:'samsung',
            rating:4.5,
            numReviews:10,
            description:'highr quality product',
        },
        {
            _id:'5',
            name:'headphone',
            category:'shirts',
            image:'/images/p-1.jpeg',
            price:120,
            brand:'samsung',
            rating:4.5,
            numReviews:10,
            description:'highr quality product',
        },
        {
            _id:'6',
            name:'headphone',
            category:'shirts',
            image:'/images/p-1.jpeg',
            price:160,
            brand:'samsung',
            rating:4.5,
            numReviews:10,
            description:'highr quality product',
        },
    ],
};


export default data;